version: "3"
services:
  datascience-notebook:
      image: jupyter/datascience-notebook
      volumes:
        - .trabquad.ipynb:/work/trabquad.ipynb
      ports:
        - 8888:8888
      container_name:   datascience-notebook-container