version: "3"
services:
  datascience-notebook:
      image: jupyter/datascience-notebook
      volumes:
        - /workspace/minimoquadrados/data/:/work/
      ports:
        - 8888:8888
      container_name:   datascience-notebook-container

